scrapper:
  messages:
    errors:
      badRequest: "Некорректные параметры запроса"
      chatNotFound: "Чат не существует"
      linkNotFound: "Ссылка не найдена в списке отслеживания"
      linkAlreadyTracked: "Ссылка уже отслеживается"
      chatAlreadyRegistered: "Чат уже существует"
      processingError: "Ошибка: не удалось обработать эту ссылку. Возможно, ресурс недоступен."

    updates:
      githubUpdate: "Новый %s: %s\nАвтор: %s\nСоздано: %s\n\n%s"
      githubNoDescription: "*Нет описания*"
      stackoverflowUpdate: "%s в вопросе: %s\nАвтор: %s\nСоздано: %s\n\n%s"
      stackoverflowNoDescription: "*Нет текста*"
