server:
  port: 8081

spring:
  application:
    name: scrapper
  config:
    import:
      - optional:file:scrapper/config/messages.yml
      - optional:file:config/messages.yml

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: false
    change-log: classpath:migrations/master.xml

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      schema.registry.url: ${KAFKA_SCHEMA_REGISTRY_URL}
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true

  data:
    redis:
      password: ${VALKEY_PASSWORD}
      cluster:
        nodes: ${SCRAPPER_VALKEY_CLUSTER_NODES}
      lettuce:
        cluster:
          refresh:
            adaptive: true
            period: 60s

app:
  bot:
    base-url: ${BOT_URL:http://localhost:8080}

  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10m
    batch-size: 200
    threads-count: 4

  links:
    limit: 100

  valkey:
    cache:
      client-side:
        enabled: ${SCRAPPER_VALKEY_CLIENT_SIDE_CACHE_ENABLED:true}
        max-size: 10000

  cache:
    ttl: ${VALKEY_TTL:10m}

  stackoverflow:
    base-url: https://api.stackexchange.com/2.2
    key: ${STACKOVERFLOW_KEY}
    access-token: ${STACKOVERFLOW_ACCESS_KEY}

  github:
    base-url: https://api.github.com
    token: ${GITHUB_TOKEN}

  database:
    #SQL или ORM
    access-type: ORM

  use-queue: true
  kafka:
    topic: ${KAFKA_TOPIC_LINK_UPDATES}
    partitions: ${KAFKA_TOPIC_PARTITIONS:1}
    replicas: ${KAFKA_TOPIC_REPLICAS:1}

  use-outbox: true
  outbox:
    interval: 5000
    batch-size: 100
