server:
  port: 8081

spring:
  application:
    name: scrapper
  config:
    import:
      - optional:file:scrapper/config/messages.yml
      - optional:file:config/messages.yml

  datasource:
    url: jdbc:postgresql://localhost:54321/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

app:
  bot:
    base-url: http://localhost:8080
  scheduler:
    enable: true
    interval: 10s
  stackoverflow:
    base-url: https://api.stackexchange.com/2.2
    key: ${STACKOVERFLOW_KEY} # Use env variable. DO NOT KEEP TOKEN HERE
    access-token: ${STACKOVERFLOW_ACCESS_KEY} # Use env variable. DO NOT KEEP TOKEN HERE
  github:
    base-url: https://api.github.com
    token: ${GITHUB_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE

  database:
    access-type: JPA # Переключатель: JDBC или JPA

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){faint} %clr(%5p) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m %clr(%kvp){yellow}%n%wEx"
