server:
  port: 8081

spring:
  application:
    name: scrapper
  config:
    import:
      - optional:file:scrapper/config/messages.yml
      - optional:file:config/messages.yml

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: false
    change-log: classpath:migrations/master.xml

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

app:
  bot:
    base-url: ${BOT_URL:http://localhost:8080}
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10m
    batch-size: 50

  links:
    limit: 100

  stackoverflow:
    base-url: https://api.stackexchange.com/2.2
    key: ${STACKOVERFLOW_KEY}
    access-token: ${STACKOVERFLOW_ACCESS_KEY}

  github:
    base-url: https://api.github.com
    token: ${GITHUB_TOKEN}

  database:
    #SQL или ORM
    access-type: ORM
