/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package backend.academy.linktracker.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class LinkUpdateAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3932304283561887181L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LinkUpdateAvro\",\"namespace\":\"backend.academy.linktracker.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"url\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"description\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"tgChatIds\",\"type\":{\"type\":\"array\",\"items\":\"long\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LinkUpdateAvro> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LinkUpdateAvro> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<LinkUpdateAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<LinkUpdateAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<LinkUpdateAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this LinkUpdateAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a LinkUpdateAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a LinkUpdateAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static LinkUpdateAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long id;
  private java.lang.String url;
  private java.lang.String description;
  private java.util.List<java.lang.Long> tgChatIds;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LinkUpdateAvro() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param url The new value for url
   * @param description The new value for description
   * @param tgChatIds The new value for tgChatIds
   */
  public LinkUpdateAvro(java.lang.Long id, java.lang.String url, java.lang.String description, java.util.List<java.lang.Long> tgChatIds) {
    this.id = id;
    this.url = url;
    this.description = description;
    this.tgChatIds = tgChatIds;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return url;
    case 2: return description;
    case 3: return tgChatIds;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: url = value$ != null ? value$.toString() : null; break;
    case 2: description = value$ != null ? value$.toString() : null; break;
    case 3: tgChatIds = (java.util.List<java.lang.Long>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'url' field.
   * @return The value of the 'url' field.
   */
  public java.lang.String getUrl() {
    return url;
  }


  /**
   * Sets the value of the 'url' field.
   * @param value the value to set.
   */
  public void setUrl(java.lang.String value) {
    this.url = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return The value of the 'description' field.
   */
  public java.lang.String getDescription() {
    return description;
  }


  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.String value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'tgChatIds' field.
   * @return The value of the 'tgChatIds' field.
   */
  public java.util.List<java.lang.Long> getTgChatIds() {
    return tgChatIds;
  }


  /**
   * Sets the value of the 'tgChatIds' field.
   * @param value the value to set.
   */
  public void setTgChatIds(java.util.List<java.lang.Long> value) {
    this.tgChatIds = value;
  }

  /**
   * Creates a new LinkUpdateAvro RecordBuilder.
   * @return A new LinkUpdateAvro RecordBuilder
   */
  public static backend.academy.linktracker.avro.LinkUpdateAvro.Builder newBuilder() {
    return new backend.academy.linktracker.avro.LinkUpdateAvro.Builder();
  }

  /**
   * Creates a new LinkUpdateAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LinkUpdateAvro RecordBuilder
   */
  public static backend.academy.linktracker.avro.LinkUpdateAvro.Builder newBuilder(backend.academy.linktracker.avro.LinkUpdateAvro.Builder other) {
    if (other == null) {
      return new backend.academy.linktracker.avro.LinkUpdateAvro.Builder();
    } else {
      return new backend.academy.linktracker.avro.LinkUpdateAvro.Builder(other);
    }
  }

  /**
   * Creates a new LinkUpdateAvro RecordBuilder by copying an existing LinkUpdateAvro instance.
   * @param other The existing instance to copy.
   * @return A new LinkUpdateAvro RecordBuilder
   */
  public static backend.academy.linktracker.avro.LinkUpdateAvro.Builder newBuilder(backend.academy.linktracker.avro.LinkUpdateAvro other) {
    if (other == null) {
      return new backend.academy.linktracker.avro.LinkUpdateAvro.Builder();
    } else {
      return new backend.academy.linktracker.avro.LinkUpdateAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for LinkUpdateAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LinkUpdateAvro>
    implements org.apache.avro.data.RecordBuilder<LinkUpdateAvro> {

    private long id;
    private java.lang.String url;
    private java.lang.String description;
    private java.util.List<java.lang.Long> tgChatIds;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(backend.academy.linktracker.avro.LinkUpdateAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.url)) {
        this.url = data().deepCopy(fields()[1].schema(), other.url);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.description)) {
        this.description = data().deepCopy(fields()[2].schema(), other.description);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.tgChatIds)) {
        this.tgChatIds = data().deepCopy(fields()[3].schema(), other.tgChatIds);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing LinkUpdateAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(backend.academy.linktracker.avro.LinkUpdateAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.url)) {
        this.url = data().deepCopy(fields()[1].schema(), other.url);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.description)) {
        this.description = data().deepCopy(fields()[2].schema(), other.description);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.tgChatIds)) {
        this.tgChatIds = data().deepCopy(fields()[3].schema(), other.tgChatIds);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public backend.academy.linktracker.avro.LinkUpdateAvro.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public backend.academy.linktracker.avro.LinkUpdateAvro.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'url' field.
      * @return The value.
      */
    public java.lang.String getUrl() {
      return url;
    }


    /**
      * Sets the value of the 'url' field.
      * @param value The value of 'url'.
      * @return This builder.
      */
    public backend.academy.linktracker.avro.LinkUpdateAvro.Builder setUrl(java.lang.String value) {
      validate(fields()[1], value);
      this.url = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'url' field has been set.
      * @return True if the 'url' field has been set, false otherwise.
      */
    public boolean hasUrl() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'url' field.
      * @return This builder.
      */
    public backend.academy.linktracker.avro.LinkUpdateAvro.Builder clearUrl() {
      url = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.String getDescription() {
      return description;
    }


    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public backend.academy.linktracker.avro.LinkUpdateAvro.Builder setDescription(java.lang.String value) {
      validate(fields()[2], value);
      this.description = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public backend.academy.linktracker.avro.LinkUpdateAvro.Builder clearDescription() {
      description = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'tgChatIds' field.
      * @return The value.
      */
    public java.util.List<java.lang.Long> getTgChatIds() {
      return tgChatIds;
    }


    /**
      * Sets the value of the 'tgChatIds' field.
      * @param value The value of 'tgChatIds'.
      * @return This builder.
      */
    public backend.academy.linktracker.avro.LinkUpdateAvro.Builder setTgChatIds(java.util.List<java.lang.Long> value) {
      validate(fields()[3], value);
      this.tgChatIds = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'tgChatIds' field has been set.
      * @return True if the 'tgChatIds' field has been set, false otherwise.
      */
    public boolean hasTgChatIds() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'tgChatIds' field.
      * @return This builder.
      */
    public backend.academy.linktracker.avro.LinkUpdateAvro.Builder clearTgChatIds() {
      tgChatIds = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LinkUpdateAvro build() {
      try {
        LinkUpdateAvro record = new LinkUpdateAvro();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.url = fieldSetFlags()[1] ? this.url : (java.lang.String) defaultValue(fields()[1]);
        record.description = fieldSetFlags()[2] ? this.description : (java.lang.String) defaultValue(fields()[2]);
        record.tgChatIds = fieldSetFlags()[3] ? this.tgChatIds : (java.util.List<java.lang.Long>) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LinkUpdateAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<LinkUpdateAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LinkUpdateAvro>
    READER$ = (org.apache.avro.io.DatumReader<LinkUpdateAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.id);

    out.writeString(this.url);

    out.writeString(this.description);

    long size0 = this.tgChatIds.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.Long e0: this.tgChatIds) {
      actualSize0++;
      out.startItem();
      out.writeLong(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readLong();

      this.url = in.readString();

      this.description = in.readString();

      long size0 = in.readArrayStart();
      java.util.List<java.lang.Long> a0 = this.tgChatIds;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.Long>((int)size0, SCHEMA$.getField("tgChatIds").schema());
        this.tgChatIds = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.Long> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.Long>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.Long e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readLong();
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readLong();
          break;

        case 1:
          this.url = in.readString();
          break;

        case 2:
          this.description = in.readString();
          break;

        case 3:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.Long> a0 = this.tgChatIds;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.Long>((int)size0, SCHEMA$.getField("tgChatIds").schema());
            this.tgChatIds = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.Long> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.Long>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.Long e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readLong();
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










