bot:
  messages:
    start: "Добро пожаловать! Используйте /help"
    help: |
      Доступные команды:
      /start - Запуск бота
      /help - Справка
      /track - Отслеживать ссылку
      /untrack [ссылка] - Прекратить отслеживание
      /list [тег] - Список ссылок
    wrong: "Неизвестная команда. Используйте /help"
    cancel: "Текущее действие отменено"

    track:
      linkRequest: "Отправьте ссылку для отслеживания (GitHub/StackOverflow)"
      invalidLink: "Некорректная ссылка. Поддерживаются GitHub/StackOverflow"
      alreadyTracked: "Ссылка уже отслеживается"
      tagRequest: "Теги (через запятую, опционально) или /cancel"
      success: "Ссылка добавлена в отслеживание"
    untrack:
      success: "Отслеживание прекращено"
      notFound: "Ссылка не найдена в отслеживании"
    listMsg:
      empty: "У вас нет отслеживаемых ссылок"
      title: "Ваши ссылки:"
